# Generated by Django 4.1.1 on 2022-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_App_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='año',
            new_name='ano',
        ),
        migrations.AlterField(
            model_name='autos',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='autos',
            name='modelo',
            field=models.CharField(max_length=20),
        ),
    ]
