# Generated by Django 4.1.1 on 2022-10-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_App_2', '0002_rename_año_autos_ano_alter_autos_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='ano',
            new_name='año',
        ),
    ]
