# Generated by Django 4.1.2 on 2022-11-10 01:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_App_2', '0005_alter_autos_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
