# Generated by Django 4.1.1 on 2022-10-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
