# Generated by Django 4.1.1 on 2022-10-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_App', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Humano',
            new_name='Persona',
        ),
    ]
